"use client";

import { useEffect, useState } from "react";

const heroTitles = [
  'console.log("Hello!")', 'print("You\'ve arrived")', 'cout << "at a place";',
  'content: "where code"', 'echo "meets creativity!"', 'printf("Let\'s build");',
  "<p>something cool</p>", 'out.println("together!");', 'Console.Write(":D");',
];
const posters = ["sumfun.webp", "starlight.webp", "prosperity toss.webp", "freaky funhouse.webp", "freaky funhouse ticket front.webp", "unspoken.webp", "lazarus.webp", "closeted lies.webp", "minnie.webp", "better life.webp"];

function SectionNumber({ number, right = false }) {
  return <div className={`hidden lg:block absolute top-0 ${right ? "right-14" : "left-14"}`}><div className="w-4 h-32 mb-2 shadow-xl bg-gray-600 dark:bg-gray-50" /><p className="text-gray-600 dark:text-gray-50 font-mono font-bold text-3xl absolute">{number}</p></div>;
}

function SectionHeader({ heading, subtitle, gradient = "moving-gradient-1" }) {
  return <header className="py-10 md:py-24 text-center relative overflow-hidden"><div className={`absolute inset-0 -z-0 ${gradient}`} /><div className="relative bg-gray-50 z-10 dark:bg-gray-900 shadow-xl p-5 lg:p-10 inline-block w-fit mx-5"><h2 className="text-4xl md:text-4xl lg:text-5xl mb-2 font-black text-gray-700 dark:text-gray-200">{heading}</h2><p className="text-sm md:text-base lg:text-lg text-gray-600 dark:text-gray-300 max-w-xl font-semibold mx-auto">{subtitle}</p></div></header>;
}

function Navbar({ theme, setTheme }) {
  const [open, setOpen] = useState(false);
  const links = [["About", "about"], ["Experience", "experience"], ["Web dev", "web-development"], ["Game dev", "game-development"], ["Design", "graphic-design"], ["Contact", "contact"]];
  return <><nav id="navbar" className="flex items-center gap-4 px-6 lg:px-10 py-4 top-0 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md shadow-md fixed w-full z-50"><a aria-label="My logo" href="/#home" className="overflow-hidden bg-gradient-to-br from-purple-400 to-red-400 w-6 h-6 relative"><span className="logo-type text-white dark:text-gray-900 text-3xl font-black absolute bottom-0">B</span></a><a href="/#home" className="nav-text-home">Ng Bob Shoaun</a><div className="hidden lg:flex gap-9 items-center ml-auto">{links.map(([label, id]) => <a key={id} href={`/#${id}`} className="nav-text">{label}</a>)}<a href="/resume" className="nav-text">Resume</a><button title="toggle theme" aria-label="toggle theme" onClick={() => setTheme(theme === "dark" ? "light" : "dark")} className="text-sm font-semibold border-gray-500 border-2 hover:bg-gray-200 dark:hover:bg-gray-700 py-1.5 px-3 dark:text-gray-50 rounded-md">{theme === "dark" ? "Dark" : "Light"}</button></div><button title="Navigation Menu" aria-label="Navigation Menu" onClick={() => setOpen(!open)} className="lg:hidden text-lg ml-auto dark:text-white"><i className="fas fa-bars" /></button></nav>{open && <dialog open className="fixed top-0 left-0 right-0 z-50 p-0 py-4 shadow-2xl w-full bg-white dark:bg-gray-900"><div className="text-right py-2 px-2"><button aria-label="Close navigation menu" onClick={() => setOpen(false)} className="text-lg text-gray-800 dark:text-gray-50 bg-gray-50 dark:bg-gray-800 px-3 py-1"><i className="fas fa-times" /></button></div><div className="mb-3 text-center font-mono text-gray-800 dark:text-gray-50 space-y-2">{links.map(([label, id]) => <a key={id} onClick={() => setOpen(false)} className="block bg-gray-50 dark:bg-gray-800 p-5" href={`/#${id}`}>{label}</a>)}<a onClick={() => setOpen(false)} className="block bg-gray-50 dark:bg-gray-800 p-5" href="/resume">Resume</a></div><div className="text-center"><button onClick={() => setTheme(theme === "dark" ? "light" : "dark")} className="border-gray-500 border-2 py-2 px-4 dark:text-gray-50 rounded-md">{theme === "dark" ? "Dark" : "Light"}</button></div></dialog>}</>;
}

function Hero() {
  const [index, setIndex] = useState(0);
  useEffect(() => { const timer = setInterval(() => setIndex((value) => (value + 1) % heroTitles.length), 3000); return () => clearInterval(timer); }, []);
  return <section id="home" className="relative main bg-gray-100 h-screen flex bg-gradient-to-b dark:from-gray-700 dark:to-gray-900"><div className="absolute top-0 right-0 h-1/2 w-full md:w-1/3 md:h-full moving-gradient-1" /><section className="m-auto pt-5 relative grow max-w-5xl"><div className="bg-white dark:bg-gray-900 px-5 py-10 lg:py-14 lg:px-10 shadow-2xl"><div className="bg-purple-400 dark:bg-purple-300 shadow-lg w-8 h-1.5 lg:w-10 lg:h-2 ml-0.5 mb-6" /><div className="mb-2 md:mb-5 relative hero-title"><h1 className="inline-block whitespace-nowrap overflow-hidden border-r-[3px] border-gray-600 dark:border-white font-mono font-black text-xl sm:text-2xl md:text-3xl lg:text-5xl text-gray-700 dark:text-white">{heroTitles[index]}</h1></div><p className="text-sm md:text-lg lg:text-xl mb-8 font-bold text-gray-500 dark:text-gray-400 ml-1">I design and build industry standard web experiences. Welcome to my website.</p><div className="text-xs md:text-sm text-gray-700 font-semibold font-mono"><a href="/resume" className="transition-colors px-4 py-1 mr-3 lg:ml-1 inline-block bg-green-200 shadow-lg border rounded-sm border-green-400 hover:bg-green-300">View Resume</a><a href="#contact" className="transition-colors px-4 py-1 inline-block bg-blue-200 shadow-lg hover:bg-blue-300 rounded-sm border border-blue-400">Let's talk</a></div></div></section><button title="Go to about me" aria-label="Go to about me" onClick={() => document.getElementById("about")?.scrollIntoView()} className="group text-xl lg:text-3xl py-5 text-gray-700 dark:text-white absolute w-14 mx-auto text-center bottom-20 right-0 left-0"><i className="hover-vertical fas fa-angle-down" /></button></section>;
}

function About() { return <section id="about" className="overflow-hidden snap-center relative bg-gray-50 bg-gradient-to-b dark:from-gray-800 dark:to-gray-700"><SectionNumber number="001" /><section className="main my-20 md:mb-40 md:mt-40 lg:mt-64"><div className="flex flex-col items-center gap-32 lg:gap-20 lg:flex-row justify-center"><div className="max-w-xs z-10 flex-1 bg-gray-50 dark:bg-gray-300 shadow-2xl overflow-hidden p-3 rounded-sm"><img loading="lazy" src="/images/me.webp" alt="Bob Shoaun in Banff" /></div><div className="flex-1 max-w-prose relative bg-white dark:bg-gray-900 px-6 py-6 lg:py-10 lg:px-10 shadow-2xl"><h2 className="tracking-wide text-5xl md:text-6xl lg:text-7xl font-black text-gray-700 dark:text-gray-200 mb-7">ABOUT ME</h2><div className="text-gray-600 dark:text-gray-300 lg:text-lg space-y-5"><p>Hey there! I'm Bob Shoaun Ng, a passionate software developer specializing in web development. I hold an Honours Bachelor of Science in Computer Science from the University of Toronto and proudly call both Malaysia and Toronto, Canada home.</p><p>From a young age, I've been driven by the thrill of creating and innovating. My expertise lies in JavaScript, CSS, the MERN stack, blockchain technology, and Web3.</p><p>Beyond coding, you'll find me playing table tennis, cycling, jamming on the drums, or listening to music.</p></div></div></div></section></section>; }

function Experience() { const [items, setItems] = useState([]); useEffect(() => { fetch("/experience.json").then((response) => response.json()).then(setItems); }, []); return <section id="experience" className="overflow-hidden bg-gray-100 relative bg-gradient-to-b dark:from-gray-900 dark:to-gray-800"><SectionNumber number="010" right /><header className="px-5 relative lg:flex pt-20 md:pt-40 pb-10 md:pb-24 gap-10 text-center"><h2 className="basis-1/2 lg:text-right tracking-wide text-4xl md:text-5xl lg:text-7xl font-black text-gray-700 dark:text-gray-200 mb-4">EXPERIENCE</h2><p className="basis-1/2 text-base lg:text-lg text-gray-600 dark:text-gray-300 lg:text-left lg:max-w-sm mx-auto font-semibold">Having over four years of experience and counting, here are some incredible companies I've had the privilege to work at.</p></header><section className="main max-w-6xl mx-auto mb-20 md:mb-40 relative z-10"><div className="grid grid-cols-1 md:grid-cols-2 mx-6 sm:mx-28 md:mx-0 lg:mx-20 xl:mx-28 shadow-2xl">{items.map((item) => <button key={item.name} className={`exp text-left aspect-square flex ${item.background}`}><img loading="lazy" className="m-auto h-40 sm:h-52 md:h-48 lg:h-40 aspect-square object-scale-down" src={item.logo} alt={`logo for ${item.name}`} style={{ mixBlendMode: item.blend }} /><div className="exp-desc bg-gray-100/80 dark:bg-gray-800/80 p-5 sm:p-10 md:p-5 backdrop-blur-md"><h3 className="font-bold text-gray-700 dark:text-white text-xl">{item.position}</h3><h4 className={`font-bold ${item.highlight} text-lg mb-1`}>@{item.name}</h4><p className="text-gray-500 dark:text-gray-400 mb-5 font-mono text-sm">{item.start} - {item.end}</p><ul className="text-base font-semibold text-gray-700 dark:text-gray-200 list-square ml-4">{item.points?.map((point) => <li key={point} className="mt-1">{point}</li>)}</ul></div></button>)}</div></section></section>; }

function Project({ project, game = false, right = false }) { return <article style={game ? { gridColumn: project.span || "span 4" } : undefined} className={game ? "" : "mx-3 sm:mx-14 lg:mx-0"}><div className={game ? "" : "flex flex-col lg:flex-row items-center justify-between gap-8 lg:gap-14"}><div className={game ? "z-10 max-h-80 w-fit mx-auto shadow-xl overflow-hidden" : "lg:max-w-1/2 basis-1/2"}>{game ? (project.video ? <video autoPlay loop muted controls playsInline src={project.video} className="max-h-[inherit] w-auto" /> : <img src={project.image} className="max-h-[inherit] w-auto" alt={`Screenshot of ${project.name}`} />) : <img className="max-h-80 w-auto object-scale-down shadow-xl" src={project.image} alt={`Screenshot of ${project.name}`} loading="lazy" />}</div><section className={game ? "-mt-5 px-5 pt-10 pb-5 bg-gray-50 dark:bg-gray-900 shadow-xl rounded-sm h-fit" : `basis-1/2 ${right ? "lg:order-first" : ""}`}><h3 className="text-2xl lg:text-4xl font-extrabold text-gray-800 dark:text-gray-50 mb-1">{project.name} <time className="ml-0.5 font-light text-xl lg:text-2xl dark:text-gray-300">{project.year}</time></h3><p className="font-bold font-mono text-sm text-purple-700 dark:text-purple-400 mb-3">{project.collaborators}</p><hr className="mb-4 border-gray-400 dark:border-gray-500" /><p className="text-sm md:text-base mb-4 text-gray-600 dark:text-gray-300 leading-relaxed max-w-prose">{project.description}</p><div className="text-sm font-mono font-semibold flex flex-wrap gap-2 mb-6">{project.technologies?.map((tech) => <span key={tech} className={game ? "bg-green-200 text-green-900 px-2" : "bg-red-200 text-red-900 px-2"}>{tech}</span>)}</div>{(project.github || project.website) && <div className="flex items-center justify-end gap-5">{project.github && <a href={project.github} target="_blank" rel="noreferrer" className="px-3 py-1.5 bg-gray-200 dark:bg-gray-700 text-gray-500 dark:text-gray-50">Github</a>}{project.website && <a href={project.website} target="_blank" rel="noreferrer" className="hover:underline text-gray-800 dark:text-gray-50">Link <i className="fas fa-external-link-alt ml-2" /></a>}</div>}</section></div></article>; }

function Projects({ game = false }) { const [items, setItems] = useState([]); const [expanded, setExpanded] = useState(false); useEffect(() => { fetch(game ? "/projects_game.json" : "/projects_web.json").then((response) => response.json()).then(setItems); }, [game]); const visible = items.slice(0, expanded ? items.length : game ? 5 : 4); return <section id={game ? "game-development" : "web-development"} className="relative overflow-hidden bg-gray-100 bg-gradient-to-b dark:from-gray-900 dark:to-gray-800"><SectionHeader heading={game ? "GAME DEVELOPMENT" : "WEB DEVELOPMENT"} gradient={game ? "moving-gradient-2" : "moving-gradient-1"} subtitle={game ? "Game development was what got me into coding in the first place, here are some featured projects." : "Here are some of my featured works that showcase my skills and expertise in fullstack web development."} /><SectionNumber number={game ? "100" : "011"} right={game} /><section className="main max-w-7xl py-20 md:pb-40 md:pt-32 mx-auto"><div className={game ? "space-y-20 md:space-y-36 lg:space-y-0 lg:grid lg:grid-cols-8 gap-x-20 gap-y-36" : "space-y-20 md:space-y-40"}>{visible.map((project, index) => <Project key={project.name} project={project} game={game} right={index % 2 === 1} />)}</div><button onClick={() => setExpanded(!expanded)} className="mt-20 w-full flex items-center gap-2 group font-semibold text-gray-700 dark:text-gray-100"><hr className="flex-1 border-gray-400" />{expanded ? "Less Projects" : "More Projects"}<hr className="flex-1 border-gray-400" /></button></section></section>; }

function Designs() { const [index, setIndex] = useState(0); const move = (amount) => setIndex((current) => (current + amount + posters.length) % posters.length); return <section id="graphic-design" className="overflow-hidden relative bg-gray-50 dark:bg-gray-900"><SectionNumber number="101" /><header className="px-5 relative lg:flex pt-20 md:pt-40 pb-24 gap-10 text-center"><h2 className="basis-1/2 lg:text-right tracking-wide text-4xl md:text-5xl lg:text-7xl font-black text-gray-700 dark:text-gray-200 mb-4">GRAPHIC DESIGN</h2><p className="basis-1/2 text-base lg:text-lg text-gray-600 dark:text-gray-300 lg:text-left lg:max-w-sm mx-auto font-semibold">I also have an eye for good typography and graphic designs. Here are some of my work designing posters for university clubs and events.</p></header><section className="main max-w-6xl mx-auto mb-40 flex items-center justify-center gap-10"><button aria-label="previous poster" onClick={() => move(-1)} className="bg-gray-200 dark:bg-gray-800 p-5"><i className="fas fa-caret-left text-4xl" /></button><img className="border-[0.75rem] md:border-[1.25rem] border-white shadow-2xl max-w-md" src={`/images/designs/${posters[index]}`} alt={`${posters[index]} poster`} /><button aria-label="next poster" onClick={() => move(1)} className="bg-gray-200 dark:bg-gray-800 p-5"><i className="fas fa-caret-right text-4xl" /></button></section></section>; }

function Contact() { const [status, setStatus] = useState(""); const submit = async (event) => { event.preventDefault(); const form = event.currentTarget; const response = await fetch(form.action, { method: "POST", headers: { Accept: "application/x-www-form-urlencoded;charset=UTF-8", "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8" }, body: new URLSearchParams(new FormData(form)).toString() }); setStatus(response.ok ? "Thank you for your message!" : "Message failed. Please email me directly."); if (response.ok) form.reset(); }; return <section id="contact" className="main overflow-hidden relative bg-gray-100 bg-gradient-to-b dark:from-gray-800 dark:to-gray-900"><SectionNumber number="110" right /><section className="section relative py-32 lg:py-52"><div className="bg-gray-50 dark:bg-gray-900 shadow-2xl px-5 md:px-7 py-10 lg:px-10 lg:py-14"><div className="bg-purple-400 w-8 h-1.5 mb-6" /><div className="lg:flex gap-10"><div className="basis-2/5"><h2 className="text-gray-700 dark:text-gray-200 tracking-wide text-4xl md:text-5xl lg:text-6xl font-black mb-2">CONTACT ME</h2><p className="text-sm md:text-base text-gray-500 dark:text-gray-300 mb-7">Shoot me a message and I will get back to you as soon as I can. My email is <a className="underline" href="mailto:ngbobshoaun2000@gmail.com">ngbobshoaun2000@gmail.com</a>.</p></div><form aria-label="contact form" onSubmit={submit} name="contact" action="/" method="POST" data-netlify="true" className="basis-3/5"><input type="hidden" name="form-name" value="contact" /><input name="name" className="w-full mb-4 px-4 py-2 bg-gray-300 dark:bg-gray-600 dark:text-gray-50" type="text" placeholder="Your name" required /><input name="email" className="w-full mb-4 px-4 py-2 bg-gray-300 dark:bg-gray-600 dark:text-gray-50" type="email" placeholder="Your email" required /><textarea name="message" className="w-full px-4 py-2 mb-4 bg-gray-200 dark:bg-gray-700 dark:text-gray-50" placeholder="Tell me what you think!" rows="6" required /><button type="submit" className="bg-purple-200 rounded-sm border border-purple-400 text-gray-700 py-1 px-4 ml-auto block font-semibold">Send</button>{status && <p className="mt-3 text-sm text-gray-600 dark:text-gray-300">{status}</p>}</form></div></div></section></section>; }

function Footer() { return <footer className="main shadow-2xl py-32 z-50 bg-gray-50 dark:bg-gray-700 bg-gradient-to-b dark:from-gray-800 dark:to-gray-900"><ul className="flex justify-center gap-6 mb-8"><li><a title="GitHub" href="https://github.com/BobShoaun" target="_blank" rel="noreferrer" className="nav-text p-1"><i className="fab fa-github fa-lg" /></a></li><li><a title="LinkedIn" href="https://www.linkedin.com/in/ngbobshoaun/" target="_blank" rel="noreferrer" className="nav-text p-1"><i className="fab fa-linkedin-in fa-lg" /></a></li><li><a title="Email" href="mailto:ngbobshoaun2000@gmail.com" className="nav-text p-1"><i className="far fa-envelope fa-lg" /></a></li><li><a title="Codepen" href="https://codepen.io/bobshoaun" target="_blank" rel="noreferrer" className="nav-text p-1"><i className="fab fa-codepen fa-lg" /></a></li></ul><div className="text-center"><a className="nav-text !text-xs md:text-sm text-gray-700 dark:text-gray-50" href="https://github.com/BobShoaun/Portfolio-V2" target="_blank" rel="noreferrer">Designed & Built by Ng Bob Shoaun &copy; {new Date().getFullYear()}</a></div></footer>; }

export default function Home() { const [theme, setTheme] = useState("dark"); useEffect(() => { const stored = localStorage.getItem("theme") || "dark"; setTheme(stored); document.documentElement.style.setProperty("--theme", stored); }, []); const changeTheme = (value) => { setTheme(value); localStorage.setItem("theme", value); document.documentElement.style.setProperty("--theme", value); }; return <div className={theme === "dark" ? "dark flex flex-col" : "flex flex-col"}><Navbar theme={theme} setTheme={changeTheme} /><main className="snap-y"><Hero /><About /><Experience /><Projects /><Projects game /><Designs /><Contact /></main><Footer /></div>; }